### ISSUE TITLE
Missing ClientCompletionTypes

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/SpongeAPI#2289]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, for this issue I would like to talk about ClientCompletionTypes.

We already had a discussion on the discord for that, but there are missing CCTs in the api.
Indeed, if we look at ClientCompletionKeys, we have the whole list of what Minecraft client could accept.

![keys](https://user-images.githubusercontent.com/25883318/106390257-c0e8a780-63e7-11eb-85e5-b2eb7af663ad.png)

The problem is that we are overly too restricted when we use the `Command.Parametrized` way to build commands.

For example I'm building a similar scoreboard api than the minecraft one for my per-world feature, and I have no way to 
accept types like operation `*=`, `/=` `%=`, etc, or the wildcard `*`.

Thanks for reading this issue.

**Comment by thibaulthenry** [comment]
Hey, now modifiers have been released. 

How can I use it to make the client accepts a custom parameter filled with :

`*=`
`+=`
`*`
`{"text":"json"}`

For example ?

**Comment by dualspiral** [comment]
Surely they are better as full blown parameters as opposed to CCTs which you have to deal with yourself?

**Comment by thibaulthenry** [comment]
I'm not sure I understand your reply clearly.

You are asking me if I would prefer that Sponge exposes Brigadier parameters that use the CCTs I would like to use ?
Instead of CCT themselves ?

**Comment by dualspiral** [comment]
Well, yes, though actually that's what I would prefer to have because that makes more sense and so that's what I'll do as opposed to a CCT.

The problem with doing it as a CCT is that it encourages plugin developers to perform their logic at parse time which is the wrong time to do it. Really, plugin developers should only be doing just enough to validate that an argument is valid so that if something fails later down the line, minimal work has been done. Validated args should be handled in the executor when the command is running.

In that sense, my question was rhetorical in trying to explain why CCTs aren't as expansive as CCKs. The theory behind the value modifiers I just implemented is that they are a safer way to be able to control the parser. The current CCTs are there because they are flexible forms that you may very well need to parse an input. Operations are kind of not that in that they are really only a choice.

As for your JSON question, look at `ResourceKeyedValueParameters.DATA_CONTAINER` - that might very well what you want it to do.

If you want your parameter to accept all of these, you should be using `FirstOf` instead because you should not be trying to merge multiple types together in a single parameter.

**Comment by thibaulthenry** [comment]
I understand your reasoning about what if Sponge should expose CCT or not.
I also understand that Operations are not something else than a simple choice.

But my problem remains in the client side, I have currently no way to make the `*` appear in blue on the client chat, whatever the way I do implement this parameter that can be filled with a star.

![star](https://user-images.githubusercontent.com/25883318/114281815-d4943800-9a40-11eb-987c-30bd022fd022.png)

**Comment by dualspiral** [comment]
Quite simply, I cannot work magic. We ultimately cannot control the client beyond what it offers. I've had to perform some significant tricks to get things working and I'm not willing to bend too much futher, there is a law of diminishing returns here.

Is it the ScoreHolder argument that you really want there? If it is, say so. I'll see what I can do to expose it, but if it's just the asterisk you want then it's not something I'm going to spend time on in the near to mid future, because it likely relies on us heavily abusing said score holder argument and the use case is minimal.

At the end of the day, Brigadier is pretty restrictive and if we want custom elements, we have to fit in with the rules Mojang set. It would be wonderful if they expanded what can go in an unquoted string but because we don't control the client, there is little to nothing we can do without spending a lot of effort for almost zero gain.

As this issue is about CCTs, I'm closing it, because as I said, they aren't really missing, more that CCKs and CCTs have very different meanings.

**Comment by thibaulthenry** [comment]
Yeah depends. I should be able to work around the score holders argument but ultimately I just need the asterisk so I can deal with it in my executor.

Actually the vanilla score holders argument will look for score holders in the server scoreboard whereas for my plugin I'm implementing per-world scoreboards. So yeah ultimately I already have all the logic for my custom parameter, but I can't fill the asterisk.

That's really annoying that we can't define custom ClientCompletionTypes, hope Mojang will give us more opportunities in the future
